name: arc25
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=3.3.8=py310h06a4308_0
  - asttokens=3.0.0=py310h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - coverage=7.6.9=py310h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py310h06a4308_1
  - ipython=8.30.0=py310h06a4308_0
  - ipywidgets=8.1.5=py310h06a4308_0
  - isort=6.0.1=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - jupyterlab_widgets=3.0.13=py310h06a4308_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.7=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.0=py310h06a4308_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=2.2.4=py310h23a989f_0
  - numpy-base=2.2.4=py310hee5b745_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=py310h06a4308_0
  - pandas=2.2.3=py310h6a678d5_0
  - parso=0.8.4=py310h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.0=py310h06a4308_0
  - platformdirs=4.3.7=py310h06a4308_0
  - pluggy=1.5.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py310h06a4308_0
  - pylint=3.3.5=py310h06a4308_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.7.1=py310h6a678d5_1
  - pyqt6-sip=13.9.1=py310h5eee18b_1
  - pytest=8.3.4=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytoolconfig=1.2.6=py310h06a4308_0
  - pytz=2024.1=py310h06a4308_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - rope=1.13.0=py310h06a4308_0
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.15.2=py310h23a989f_1
  - setuptools=72.1.0=py310h06a4308_0
  - sip=6.10.0=py310h6a678d5_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tomlkit=0.13.2=py310h06a4308_0
  - tornado=6.4.2=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.13=py310h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - imageio==2.37.0
      - lazy-loader==0.4
      - networkx==3.4.2
      - scikit-image==0.25.2
      - tifffile==2025.3.30
prefix: /home/gbarbadillo/miniconda3/envs/arc25
